# Generated by Django 4.1.3 on 2022-11-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_ser', models.CharField(blank=True, default='', max_length=10, verbose_name='Серия паспорта')),
                ('passport_no', models.CharField(blank=True, default='', max_length=10, verbose_name='Номер паспорта')),
                ('passport_issued', models.CharField(blank=True, default='', max_length=150, verbose_name='Паспорт кем выдан')),
                ('passport_date', models.DateField(blank=True, default='', null=True, verbose_name='дата выдачи')),
                ('driver_license_ser', models.CharField(blank=True, default='', max_length=10, verbose_name='Серия ву')),
                ('driver_license_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер ву')),
                ('driver_license_date', models.DateField(blank=True, default='', null=True, verbose_name='Дата ву')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название док-та')),
                ('doc', models.FileField(blank=True, null=True, upload_to='documents')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(max_length=20, verbose_name='Номер машины')),
                ('type_auto', models.CharField(max_length=50, verbose_name='Тип машины')),
                ('brand_auto', models.CharField(max_length=50, verbose_name='Марка машины')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(verbose_name='Дата погрузки')),
                ('trip_time', models.TimeField(verbose_name='Время подачи')),
                ('trip_from', models.CharField(max_length=255, verbose_name='Место погрузки')),
                ('trip_to', models.CharField(max_length=255, verbose_name='Место выгрузки')),
                ('type_auto', models.CharField(max_length=50, verbose_name='Вид ТС')),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена рейса')),
                ('docs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TruckReestr.files')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TruckReestr.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TruckReestr.truck')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ['-trip_date', 'trip_time'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='number_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TruckReestr.truck'),
        ),
    ]
