# Generated by Django 4.0 on 2022-01-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckReestr', '0003_alter_driver_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ву'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер ву'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_ser',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия ву'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TruckReestr.truck'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_issued',
            field=models.CharField(blank=True, max_length=150, verbose_name='Паспорт кем выдан'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_ser',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
