# Generated by Django 4.0 on 2022-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckReestr', '0005_alter_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Док-ты'),
        ),
    ]
